version: '3'

services:
    gitui:
        image: saramorillon/git-ui:latest
        container_name: gitui
        restart: always
        ports:
            - 127.0.0.1:3000:3000
        volumes:
            - ./db:/app/db
            - ./logs:/app/logs
        environment:
            - NODE_ENV=
            - APP_KEY=
            - COOKIE_NAME=
            - LOG_LEVEL=
            - REPO_DIR=
